### ISSUE TITLE
Log successful SoftEther connections to IPBan log file.

### ISSUE THREAD

**Issue by digi-Phil** [TheTitanrain/IPBan#1]
Thank you for creating this, tried it and it works great. Just had to change path from:
C:\Program Files\SoftEther VPN Server Developer Edition\security_log\...
-to-
C:\Program Files\SoftEther VPN Server\security_log\...
 in order to get it to work.
Is it possible to also add section SuccessfulLoginRegex so it will also log successful SoftEther connections to IPBan log file?

---Update---
To answer my own question, this seems to be working OK:
`
<SuccessfulLoginRegex>
    <![CDATA[
        ^(?<timestamp>.*?)(?:\sThe\sconnection).*IP\saddress:\s(?<ipaddress>(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])),.*\n.*Successfully\sauthenticated\sas\suser\s"(?<username>[^;]+?)"\.$
    ]]>
  </SuccessfulLoginRegex>
`

**Comment by TheTitanrain** [comment]
That's great to hear! Adding the SuccessfulLoginRegex section to log successful SoftEther connections to the IPBan log file seems like a good idea. Your provided regex looks fine and should work well for capturing the necessary information. Thanks for sharing the solution!

**Comment by digi-Phil** [comment]
No problem and thank you again for sharing the initial code for failed logins.
Note that have tested with SoftEther Ver 4.38, Build 9760, rtm on Windows and it works OK. Not sure if it works on newer versions.
